dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
pkgname: mocks
filename: 'mocks.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/clambin/github-stars/internal/server:
    interfaces:
      Client: {}
      Store: {}
      Notifier: {}
