// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"

	"github.com/google/go-github/v76/github"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetStarGazers provides a mock function for the type Client
func (_mock *Client) GetStarGazers(ctx context.Context, repository *github.Repository) ([]*github.Stargazer, error) {
	ret := _mock.Called(ctx, repository)

	if len(ret) == 0 {
		panic("no return value specified for GetStarGazers")
	}

	var r0 []*github.Stargazer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *github.Repository) ([]*github.Stargazer, error)); ok {
		return returnFunc(ctx, repository)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *github.Repository) []*github.Stargazer); ok {
		r0 = returnFunc(ctx, repository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Stargazer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *github.Repository) error); ok {
		r1 = returnFunc(ctx, repository)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetStarGazers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStarGazers'
type Client_GetStarGazers_Call struct {
	*mock.Call
}

// GetStarGazers is a helper method to define mock.On call
//   - ctx context.Context
//   - repository *github.Repository
func (_e *Client_Expecter) GetStarGazers(ctx interface{}, repository interface{}) *Client_GetStarGazers_Call {
	return &Client_GetStarGazers_Call{Call: _e.mock.On("GetStarGazers", ctx, repository)}
}

func (_c *Client_GetStarGazers_Call) Run(run func(ctx context.Context, repository *github.Repository)) *Client_GetStarGazers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *github.Repository
		if args[1] != nil {
			arg1 = args[1].(*github.Repository)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetStarGazers_Call) Return(stargazers []*github.Stargazer, err error) *Client_GetStarGazers_Call {
	_c.Call.Return(stargazers, err)
	return _c
}

func (_c *Client_GetStarGazers_Call) RunAndReturn(run func(ctx context.Context, repository *github.Repository) ([]*github.Stargazer, error)) *Client_GetStarGazers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRepos provides a mock function for the type Client
func (_mock *Client) GetUserRepos(ctx context.Context, user string) iter.Seq2[*github.Repository, error] {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRepos")
	}

	var r0 iter.Seq2[*github.Repository, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) iter.Seq2[*github.Repository, error]); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[*github.Repository, error])
		}
	}
	return r0
}

// Client_GetUserRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRepos'
type Client_GetUserRepos_Call struct {
	*mock.Call
}

// GetUserRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
func (_e *Client_Expecter) GetUserRepos(ctx interface{}, user interface{}) *Client_GetUserRepos_Call {
	return &Client_GetUserRepos_Call{Call: _e.mock.On("GetUserRepos", ctx, user)}
}

func (_c *Client_GetUserRepos_Call) Run(run func(ctx context.Context, user string)) *Client_GetUserRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetUserRepos_Call) Return(seq2 iter.Seq2[*github.Repository, error]) *Client_GetUserRepos_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *Client_GetUserRepos_Call) RunAndReturn(run func(ctx context.Context, user string) iter.Seq2[*github.Repository, error]) *Client_GetUserRepos_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type Store
func (_mock *Store) Add(repo *github.Repository, stargazer *github.Stargazer) (bool, error) {
	ret := _mock.Called(repo, stargazer)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*github.Repository, *github.Stargazer) (bool, error)); ok {
		return returnFunc(repo, stargazer)
	}
	if returnFunc, ok := ret.Get(0).(func(*github.Repository, *github.Stargazer) bool); ok {
		r0 = returnFunc(repo, stargazer)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*github.Repository, *github.Stargazer) error); ok {
		r1 = returnFunc(repo, stargazer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Store_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - repo *github.Repository
//   - stargazer *github.Stargazer
func (_e *Store_Expecter) Add(repo interface{}, stargazer interface{}) *Store_Add_Call {
	return &Store_Add_Call{Call: _e.mock.On("Add", repo, stargazer)}
}

func (_c *Store_Add_Call) Run(run func(repo *github.Repository, stargazer *github.Stargazer)) *Store_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *github.Repository
		if args[0] != nil {
			arg0 = args[0].(*github.Repository)
		}
		var arg1 *github.Stargazer
		if args[1] != nil {
			arg1 = args[1].(*github.Stargazer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Add_Call) Return(b bool, err error) *Store_Add_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Store_Add_Call) RunAndReturn(run func(repo *github.Repository, stargazer *github.Stargazer) (bool, error)) *Store_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Store
func (_mock *Store) Delete(repo *github.Repository, stargazer *github.Stargazer) (bool, error) {
	ret := _mock.Called(repo, stargazer)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*github.Repository, *github.Stargazer) (bool, error)); ok {
		return returnFunc(repo, stargazer)
	}
	if returnFunc, ok := ret.Get(0).(func(*github.Repository, *github.Stargazer) bool); ok {
		r0 = returnFunc(repo, stargazer)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*github.Repository, *github.Stargazer) error); ok {
		r1 = returnFunc(repo, stargazer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Store_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - repo *github.Repository
//   - stargazer *github.Stargazer
func (_e *Store_Expecter) Delete(repo interface{}, stargazer interface{}) *Store_Delete_Call {
	return &Store_Delete_Call{Call: _e.mock.On("Delete", repo, stargazer)}
}

func (_c *Store_Delete_Call) Run(run func(repo *github.Repository, stargazer *github.Stargazer)) *Store_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *github.Repository
		if args[0] != nil {
			arg0 = args[0].(*github.Repository)
		}
		var arg1 *github.Stargazer
		if args[1] != nil {
			arg1 = args[1].(*github.Stargazer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Delete_Call) Return(b bool, err error) *Store_Delete_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Store_Delete_Call) RunAndReturn(run func(repo *github.Repository, stargazer *github.Stargazer) (bool, error)) *Store_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// SetStargazers provides a mock function for the type Store
func (_mock *Store) SetStargazers(repository *github.Repository, stargazers []*github.Stargazer) ([]*github.Stargazer, error) {
	ret := _mock.Called(repository, stargazers)

	if len(ret) == 0 {
		panic("no return value specified for SetStargazers")
	}

	var r0 []*github.Stargazer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*github.Repository, []*github.Stargazer) ([]*github.Stargazer, error)); ok {
		return returnFunc(repository, stargazers)
	}
	if returnFunc, ok := ret.Get(0).(func(*github.Repository, []*github.Stargazer) []*github.Stargazer); ok {
		r0 = returnFunc(repository, stargazers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Stargazer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*github.Repository, []*github.Stargazer) error); ok {
		r1 = returnFunc(repository, stargazers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_SetStargazers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStargazers'
type Store_SetStargazers_Call struct {
	*mock.Call
}

// SetStargazers is a helper method to define mock.On call
//   - repository *github.Repository
//   - stargazers []*github.Stargazer
func (_e *Store_Expecter) SetStargazers(repository interface{}, stargazers interface{}) *Store_SetStargazers_Call {
	return &Store_SetStargazers_Call{Call: _e.mock.On("SetStargazers", repository, stargazers)}
}

func (_c *Store_SetStargazers_Call) Run(run func(repository *github.Repository, stargazers []*github.Stargazer)) *Store_SetStargazers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *github.Repository
		if args[0] != nil {
			arg0 = args[0].(*github.Repository)
		}
		var arg1 []*github.Stargazer
		if args[1] != nil {
			arg1 = args[1].([]*github.Stargazer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_SetStargazers_Call) Return(stargazers1 []*github.Stargazer, err error) *Store_SetStargazers_Call {
	_c.Call.Return(stargazers1, err)
	return _c
}

func (_c *Store_SetStargazers_Call) RunAndReturn(run func(repository *github.Repository, stargazers []*github.Stargazer) ([]*github.Stargazer, error)) *Store_SetStargazers_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

type Notifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifier) EXPECT() *Notifier_Expecter {
	return &Notifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type Notifier
func (_mock *Notifier) Notify(repository *github.Repository, gazers []*github.Stargazer, added bool) {
	_mock.Called(repository, gazers, added)
	return
}

// Notifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type Notifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - repository *github.Repository
//   - gazers []*github.Stargazer
//   - added bool
func (_e *Notifier_Expecter) Notify(repository interface{}, gazers interface{}, added interface{}) *Notifier_Notify_Call {
	return &Notifier_Notify_Call{Call: _e.mock.On("Notify", repository, gazers, added)}
}

func (_c *Notifier_Notify_Call) Run(run func(repository *github.Repository, gazers []*github.Stargazer, added bool)) *Notifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *github.Repository
		if args[0] != nil {
			arg0 = args[0].(*github.Repository)
		}
		var arg1 []*github.Stargazer
		if args[1] != nil {
			arg1 = args[1].([]*github.Stargazer)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Notifier_Notify_Call) Return() *Notifier_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *Notifier_Notify_Call) RunAndReturn(run func(repository *github.Repository, gazers []*github.Stargazer, added bool)) *Notifier_Notify_Call {
	_c.Run(run)
	return _c
}
